import type { QuizQuestion } from "@/types";

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ─── Mechanics ──────────────────────────────────────────────────────────────
  {
    id: "mq-001",
    topic: "mechanics",
    difficulty: 800,
    question: "A ball is dropped from rest at height h. What is its speed just before hitting the ground?",
    options: ["√(gh)", "√(2gh)", "2gh", "gh"],
    correctIndex: 1,
    explanation: "Using energy conservation: mgh = ½mv² → v = √(2gh)",
  },
  {
    id: "mq-002",
    topic: "mechanics",
    difficulty: 1200,
    question: "A 2 kg object accelerates at 3 m/s². What is the net force?",
    options: ["1.5 N", "5 N", "6 N", "12 N"],
    correctIndex: 2,
    explanation: "F = ma = 2 kg × 3 m/s² = 6 N",
  },
  {
    id: "mq-003",
    topic: "mechanics",
    difficulty: 1500,
    question: "For a simple pendulum of length L, what is the period for small oscillations?",
    questionLatex: "T = ?",
    options: ["2π√(g/L)", "2π√(L/g)", "π√(L/g)", "2√(L/g)"],
    correctIndex: 1,
    explanation: "T = 2π√(L/g) — derived from the equation of motion for small angles",
  },
  {
    id: "mq-004",
    topic: "mechanics",
    difficulty: 1800,
    question: "A 1 kg mass on a spring (k = 100 N/m) oscillates. What is the angular frequency ω?",
    options: ["10 rad/s", "100 rad/s", "√10 rad/s", "10π rad/s"],
    correctIndex: 0,
    explanation: "ω = √(k/m) = √(100/1) = 10 rad/s",
  },
  {
    id: "mq-005",
    topic: "mechanics",
    difficulty: 2000,
    question: "A projectile is launched at 45° with speed v₀. What is the maximum range?",
    questionLatex: "R_{max} = ?",
    options: ["v₀²/g", "v₀²/(2g)", "2v₀²/g", "v₀²/(4g)"],
    correctIndex: 0,
    explanation: "R = v₀²sin(2θ)/g; maximum at θ=45°: R_max = v₀²/g",
  },
  {
    id: "mq-006",
    topic: "mechanics",
    difficulty: 2200,
    question: "What is the angular momentum of a 2 kg particle moving at 5 m/s at radius 3 m?",
    options: ["10 kg·m²/s", "15 kg·m²/s", "30 kg·m²/s", "6 kg·m²/s"],
    correctIndex: 2,
    explanation: "L = mvr = 2 × 5 × 3 = 30 kg·m²/s (for circular motion with v perpendicular to r)",
  },
  {
    id: "mq-007",
    topic: "mechanics",
    difficulty: 900,
    question: "What is the gravitational potential energy of a 5 kg object at height 10 m? (g = 10 m/s²)",
    options: ["50 J", "500 J", "5000 J", "0.5 J"],
    correctIndex: 1,
    explanation: "E_p = mgh = 5 × 10 × 10 = 500 J",
  },
  {
    id: "mq-008",
    topic: "mechanics",
    difficulty: 1600,
    question: "Two objects collide perfectly inelastically. Which quantity is conserved?",
    options: ["Kinetic energy only", "Momentum only", "Both momentum and kinetic energy", "Neither"],
    correctIndex: 1,
    explanation: "In perfectly inelastic collisions, momentum is conserved but kinetic energy is not (some converts to heat/deformation)",
  },

  // ─── Electricity ────────────────────────────────────────────────────────────
  {
    id: "eq-001",
    topic: "electricity",
    difficulty: 800,
    question: "What is the resistance of a 12V circuit drawing 3A current?",
    options: ["4 Ω", "36 Ω", "0.25 Ω", "9 Ω"],
    correctIndex: 0,
    explanation: "R = V/I = 12/3 = 4 Ω",
  },
  {
    id: "eq-002",
    topic: "electricity",
    difficulty: 1100,
    question: "A 10μF capacitor is charged to 100V. How much energy is stored?",
    options: ["0.5 mJ", "5 mJ", "50 mJ", "500 mJ"],
    correctIndex: 2,
    explanation: "E = ½CV² = ½ × 10×10⁻⁶ × 100² = 0.05 J = 50 mJ",
  },
  {
    id: "eq-003",
    topic: "electricity",
    difficulty: 1400,
    question: "In an RC circuit with R=1kΩ and C=1μF, what is the time constant?",
    options: ["1 μs", "1 ms", "1 s", "1 ns"],
    correctIndex: 1,
    explanation: "τ = RC = 1000 × 10⁻⁶ = 10⁻³ s = 1 ms",
  },
  {
    id: "eq-004",
    topic: "electricity",
    difficulty: 1700,
    question: "Two charges +2μC and -3μC are 0.1m apart. The force is approximately:",
    options: ["5.4 N attractive", "5.4 N repulsive", "0.54 N attractive", "0.54 N repulsive"],
    correctIndex: 0,
    explanation: "F = kq₁q₂/r² = 8.99×10⁹ × 2×10⁻⁶ × 3×10⁻⁶ / 0.01 = 5.4 N; opposite charges → attractive",
  },
  {
    id: "eq-005",
    topic: "electricity",
    difficulty: 2100,
    question: "An LC circuit has L=4mH, C=1μF. What is the resonant frequency?",
    options: ["~796 Hz", "~2.5 kHz", "~7.96 kHz", "~25 kHz"],
    correctIndex: 1,
    explanation: "f = 1/(2π√LC) = 1/(2π√(4×10⁻³ × 10⁻⁶)) ≈ 2513 Hz ≈ 2.5 kHz",
  },
  {
    id: "eq-006",
    topic: "electricity",
    difficulty: 900,
    question: "A 60W light bulb connected to 120V. What current does it draw?",
    options: ["0.25 A", "0.5 A", "2 A", "7200 A"],
    correctIndex: 1,
    explanation: "I = P/V = 60/120 = 0.5 A",
  },

  // ─── Waves ──────────────────────────────────────────────────────────────────
  {
    id: "wq-001",
    topic: "waves",
    difficulty: 700,
    question: "Sound travels at 340 m/s. What wavelength corresponds to 440 Hz (musical A)?",
    options: ["0.58 m", "0.77 m", "1.3 m", "15 m"],
    correctIndex: 1,
    explanation: "λ = v/f = 340/440 ≈ 0.77 m",
  },
  {
    id: "wq-002",
    topic: "waves",
    difficulty: 1300,
    question: "Light passes from air (n=1) to glass (n=1.5) at 30°. What is the refraction angle?",
    options: ["~19.5°", "~30°", "~45°", "~48.6°"],
    correctIndex: 0,
    explanation: "Snell's law: sin(θ₂) = sin(30°)/1.5 = 0.5/1.5 = 1/3 → θ₂ ≈ 19.5°",
  },
  {
    id: "wq-003",
    topic: "waves",
    difficulty: 1600,
    question: "In a double slit experiment, d=0.5mm, L=2m, λ=500nm. What is the fringe spacing?",
    options: ["0.5 mm", "1 mm", "2 mm", "5 mm"],
    correctIndex: 2,
    explanation: "Δy = λL/d = 500×10⁻⁹ × 2 / 5×10⁻⁴ = 2×10⁻³ m = 2 mm",
  },
  {
    id: "wq-004",
    topic: "waves",
    difficulty: 1900,
    question: "A standing wave forms on a 1m string fixed at both ends. What is the fundamental frequency if v=200 m/s?",
    options: ["100 Hz", "200 Hz", "400 Hz", "50 Hz"],
    correctIndex: 0,
    explanation: "f₁ = v/(2L) = 200/(2×1) = 100 Hz",
  },
  {
    id: "wq-005",
    topic: "waves",
    difficulty: 1000,
    question: "A car horn sounds at 500 Hz. The car approaches at 34 m/s (v_sound = 340 m/s). Observed frequency:",
    options: ["450 Hz", "500 Hz", "550 Hz", "486 Hz"],
    correctIndex: 2,
    explanation: "f' = f·v/(v-v_s) = 500 × 340/(340-34) = 500 × 340/306 ≈ 556 Hz ≈ 550 Hz",
  },

  // ─── Thermodynamics ─────────────────────────────────────────────────────────
  {
    id: "tq-001",
    topic: "thermodynamics",
    difficulty: 800,
    question: "An ideal gas at 300K doubles in volume at constant pressure. What is the new temperature?",
    options: ["150 K", "300 K", "600 K", "900 K"],
    correctIndex: 2,
    explanation: "Charles's law: V/T = const → T₂ = T₁(V₂/V₁) = 300 × 2 = 600 K",
  },
  {
    id: "tq-002",
    topic: "thermodynamics",
    difficulty: 1200,
    question: "A gas absorbs 400 J of heat and does 150 J of work. What is ΔU?",
    options: ["250 J", "550 J", "-250 J", "-550 J"],
    correctIndex: 0,
    explanation: "ΔU = Q - W = 400 - 150 = 250 J",
  },
  {
    id: "tq-003",
    topic: "thermodynamics",
    difficulty: 1600,
    question: "A Carnot engine operates between 500K and 300K. What is its maximum efficiency?",
    options: ["40%", "60%", "25%", "75%"],
    correctIndex: 0,
    explanation: "η = 1 - T_C/T_H = 1 - 300/500 = 1 - 0.6 = 0.4 = 40%",
  },
  {
    id: "tq-004",
    topic: "thermodynamics",
    difficulty: 1900,
    question: "What is the rms speed of nitrogen (M=28 g/mol) at 300K? (R=8.314 J/mol·K)",
    options: ["~517 m/s", "~300 m/s", "~820 m/s", "~1.5 km/s"],
    correctIndex: 0,
    explanation: "v_rms = √(3RT/M) = √(3×8.314×300/0.028) ≈ 517 m/s",
  },
  {
    id: "tq-005",
    topic: "thermodynamics",
    difficulty: 1400,
    question: "How much heat is needed to raise 2 kg of water (c=4186 J/kg·K) by 10°C?",
    options: ["419 J", "4186 J", "8372 J", "83720 J"],
    correctIndex: 3,
    explanation: "Q = mcΔT = 2 × 4186 × 10 = 83720 J",
  },
];

export function getQuestionsByTopic(topic: string): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter((q) => q.topic === topic);
}

export function getQuestionById(id: string): QuizQuestion | undefined {
  return QUIZ_QUESTIONS.find((q) => q.id === id);
}
